root = "."
tmp_dir = "tmp"

[build]
  cmd = "CGO_ENABLED=1 go build -o ./tmp/server ./cmd/server/main.go"
  bin = "./tmp/server"
  full_bin = "./tmp/server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "data"]
  delay = 1000

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
